name: AWS CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: tfsec
      uses: tfsec/tfsec-sarif-action@main
      with:
        sarif_file: tfsec.sarif         

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: tfsec.sarif

    - name: Run TFSec
      run: tfsec --config-file tfsec.yml

    - name: Run TFLint
      run: tflint

#    - name: Terraform Plan
#      run: terraform plan

#  terraform-cd:
#    runs-on: ubuntu-latest

 #   steps:
 #   - name: Checkout Repository
 #     uses: actions/checkout@v2

 #   - name: Terraform Apply
 #     run: terraform apply -var "aws_credentials=$AWS_CREDENTIALS" --auto-approve
