name: AWS CI/CD

on:
  push:
    branches:
      - main

jobs:
    tfsec:
      name: tfsec sarif report
      runs-on: ubuntu-latest
      permissions:
        actions: read
        contents: read
        security-events: write

      steps:
        - name: Clone repo
          uses: actions/checkout@v2
          with:
            persist-credentials: false

        - name: tfsec
          uses: aquasecurity/tfsec-sarif-action@v0.1.0
          with:
            sarif_file: tfsec.sarif          

        - name: Upload SARIF file
          uses: github/codeql-action/upload-sarif@v1
          with:
            # Path to SARIF file relative to the root of the repository
            sarif_file: tfsec.sarif

        - uses: actions/cache@v4
          name: Cache plugin dir
          with:
            path: ~/.tflint.d/plugins
            key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    tflint:
      name: tfsec sarif report
      runs-on: ubuntu-latest

      steps:
        - uses: terraform-linters/setup-tflint@v4
          name: Setup TFLint
          with:
            tflint_version: v0.50.3
    
        - name: Show version
          run: tflint --version
    
        - name: Init TFLint
          run: tflint --init
          env:
            # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
            GITHUB_TOKEN: ${{ github.token }}
    
        - name: Run TFLint
          run: tflint -f compact

#    - name: Terraform Plan
#      run: terraform plan

#  terraform-cd:
#    runs-on: ubuntu-latest

 #   steps:
 #   - name: Checkout Repository
 #     uses: actions/checkout@v2

 #   - name: Terraform Apply
 #     run: terraform apply -var "aws_credentials=$AWS_CREDENTIALS" --auto-approve
